import { Product, User, ChatMessage } from '../App';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '+1 234-567-8900',
    avatar: '',
    verified: true,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '+1 234-567-8901',
    avatar: '',
    verified: false,
  },
  {
    id: '3',
    name: 'Mike Chen',
    email: 'mike@example.com',
    phone: '+1 234-567-8902',
    avatar: '',
    verified: true,
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'iPhone 14 Pro Max 256GB - Excellent Condition',
    price: 899,
    category: 'phones',
    condition: 'Like New',
    description: 'Barely used iPhone 14 Pro Max in pristine condition. Comes with original box, charger, and protective case. Battery health at 98%. No scratches or dents.',
    images: [
      'https://images.unsplash.com/photo-1761906976176-0559a6d130dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWFydHBob25lJTIwbW9kZXJufGVufDF8fHx8MTc2NTA5NDcxMXww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1761906976176-0559a6d130dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWFydHBob25lJTIwbW9kZXJufGVufDF8fHx8MTc2NTA5NDcxMXww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    location: 'New York, NY',
    distance: '2.5 km',
    sellerId: '1',
    postedTime: '2 hours ago',
    plan: 'premium',
    brand: 'Apple',
    model: 'iPhone 14 Pro Max',
    specifications: {
      Storage: '256GB',
      Color: 'Deep Purple',
      'Battery Health': '98%',
      Warranty: 'AppleCare+ until Dec 2025',
    },
  },
  {
    id: '2',
    title: 'MacBook Air M2 2023 - 16GB RAM, 512GB SSD',
    price: 1299,
    category: 'laptops',
    condition: 'Like New',
    description: 'Perfect condition MacBook Air with M2 chip. Used for light work only. Includes original charger and sleeve.',
    images: [
      'https://images.unsplash.com/photo-1511385348-a52b4a160dc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXB0b3AlMjBjb21wdXRlcnxlbnwxfHx8fDE3NjUxMzM4Njh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    location: 'Brooklyn, NY',
    distance: '5.3 km',
    sellerId: '2',
    postedTime: '5 hours ago',
    plan: 'featured',
    brand: 'Apple',
    model: 'MacBook Air M2',
    specifications: {
      RAM: '16GB',
      Storage: '512GB SSD',
      Color: 'Midnight',
      'Cycle Count': '12',
    },
  },
  {
    id: '3',
    title: 'Samsung 55" 4K Smart TV QLED',
    price: 650,
    category: 'tv',
    condition: 'Used',
    description: 'Samsung QLED TV in excellent working condition. Wall mount included. Moving sale.',
    images: [
      'https://images.unsplash.com/photo-1763132646264-4123ae7cf4a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWxldmlzaW9uJTIwc2NyZWVufGVufDF8fHx8MTc2NTA4NTgzN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    location: 'Manhattan, NY',
    distance: '1.2 km',
    sellerId: '3',
    postedTime: '1 day ago',
    plan: 'free',
    brand: 'Samsung',
    model: 'QN55Q80A',
    specifications: {
      Size: '55 inches',
      Resolution: '4K UHD',
      'HDR Support': 'Yes',
      'Smart Features': 'Tizen OS',
    },
  },
  {
    id: '4',
    title: 'LG Double Door Refrigerator 450L',
    price: 450,
    category: 'fridge',
    condition: 'Used',
    description: 'Reliable LG fridge with inverter compressor. Energy efficient and spacious.',
    images: [
      'https://images.unsplash.com/photo-1643356472833-5b1f2cd4ca3c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWZyaWdlcmF0b3IlMjBraXRjaGVufGVufDF8fHx8MTc2NTEyNTEwOXww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    location: 'Queens, NY',
    distance: '8.7 km',
    sellerId: '1',
    postedTime: '3 days ago',
    plan: 'free',
    brand: 'LG',
    model: 'GL-T432FPZU',
  },
  {
    id: '5',
    title: 'Daikin Inverter AC 1.5 Ton - Split Unit',
    price: 380,
    category: 'ac',
    condition: 'Used',
    description: 'Energy efficient Daikin AC with remote control. Regular servicing done.',
    images: [
      'https://images.unsplash.com/photo-1718203862467-c33159fdc504?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhaXIlMjBjb25kaXRpb25lcnxlbnwxfHx8fDE3NjUwODY1MzV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    location: 'Bronx, NY',
    distance: '12.1 km',
    sellerId: '2',
    postedTime: '1 week ago',
    plan: 'featured',
    brand: 'Daikin',
    model: 'FTKF50TV16U',
  },
  {
    id: '6',
    title: 'Canon EOS R6 Mirrorless Camera Body',
    price: 1850,
    category: 'cameras',
    condition: 'Like New',
    description: 'Professional camera in mint condition. Low shutter count. Perfect for photography enthusiasts.',
    images: [
      'https://images.unsplash.com/photo-1693208056529-03702201669e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1lcmElMjBkaWdpdGFsfGVufDF8fHx8MTc2NTE4NTUwOXww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    location: 'Manhattan, NY',
    distance: '3.4 km',
    sellerId: '3',
    postedTime: '4 hours ago',
    plan: 'premium',
    brand: 'Canon',
    model: 'EOS R6',
  },
];

export const mockChats: ChatMessage[] = [
  {
    id: '1',
    senderId: '2',
    receiverId: '1',
    message: 'Hi, is this iPhone still available?',
    timestamp: '10:30 AM',
    productId: '1',
  },
  {
    id: '2',
    senderId: '1',
    receiverId: '2',
    message: 'Yes! It is available. Would you like to see it?',
    timestamp: '10:35 AM',
    productId: '1',
  },
  {
    id: '3',
    senderId: '2',
    receiverId: '1',
    message: 'Sure! Can we meet this evening?',
    timestamp: '10:40 AM',
    productId: '1',
  },
];
